(()=>{
'use strict';
const VERSION='42.29';
function setVersion(){document.title=document.title.replace(/V42\.\d+/,'V'+VERSION);document.querySelectorAll('h1 span').forEach(x=>{if(/^V42\./.test(x.textContent.trim()))x.textContent='V'+VERSION});document.querySelectorAll('.build-badge').forEach(x=>x.textContent='MAJ '+VERSION)}
function liveUrl(){try{const t=typeof currentTour==='function'?currentTour():null;if(!t)return '';const u=new URL('./live.html',location.href);if(t.short_code)u.searchParams.set('s',String(t.short_code).toUpperCase());else{if(!S?.workspace?.public_token)return '';u.searchParams.set('public',S.workspace.public_token);u.searchParams.set('tournament',t.id)}return u.toString()}catch(_){return ''}}
function ensureLiveCard(){if(!window.S||!S.workspace||typeof currentTour!=='function')return;const t=currentTour();const view=document.getElementById('view-tournaments');if(!view||!t)return;let card=document.getElementById('sweLiveShareCard');if(!card){card=document.createElement('div');card.id='sweLiveShareCard';card.className='card';card.style.border='2px solid #b9d8ff';card.style.background='#f8fbff';view.insertAdjacentElement('afterbegin',card)}const url=liveUrl();card.innerHTML='<div class="row" style="justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><b>📡 Lien de suivi du tournoi</b><div class="muted" style="margin-top:4px">Lien séparé de l’inscription : il affiche uniquement les équipes de ce tournoi, le classement et les résultats en direct.</div></div><div class="row"><button id="sweCopyLiveLink" class="primary">Copier le lien Live</button><button id="sweOpenLiveLink">Ouvrir</button></div></div>';const copy=card.querySelector('#sweCopyLiveLink'),open=card.querySelector('#sweOpenLiveLink');copy.disabled=!url;open.disabled=!url;copy.onclick=async()=>{try{await navigator.clipboard.writeText(url);toast('Lien Live copié ✅')}catch(_){toast('Impossible de copier le lien.')}};open.onclick=()=>{if(url)window.open(url,'_blank','noopener,noreferrer')}}
function relabelAcademy(){document.querySelectorAll('#publicView *').forEach(el=>{if(el.children.length)return;const txt=el.textContent||'';if(txt.includes('Chien Boul Academy :')&&!txt.includes('Note équipe évaluée par Chien Boul Academy :'))el.textContent=txt.replace('Chien Boul Academy :','Note équipe évaluée par Chien Boul Academy :')})}
let scheduled=false;function apply(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;setVersion();ensureLiveCard();relabelAcademy()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});
})();
