(()=>{
'use strict';
const VERSION='42.36';
const COLOR_OPTS=[['#111827','Noir'],['#2563eb','Bleu'],['#f8fafc','Blanc'],['#dc2626','Rouge'],['#16a34a','Vert'],['#eab308','Jaune'],['#f97316','Orange'],['#7c3aed','Violet'],['#ec4899','Rose'],['#78350f','Marron'],['#64748b','Gris']];
const esc31=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function setVersion31(){document.title=document.title.replace(/V42\.\d+/,'V'+VERSION);document.querySelectorAll('h1 span').forEach(x=>{if(/^V42\./.test(x.textContent.trim()))x.textContent='V'+VERSION});document.querySelectorAll('.build-badge').forEach(x=>x.textContent='MAJ '+VERSION)}
function stableMention(team,score,guests){if(guests>2)return 'Trop de Guests pour une note fiable';const n=Number(score||0),pool=n>=4.2?['Très costaud','Ça promet','Gros potentiel']:n>=3.5?['Bien équilibrée','Solide sur le papier','Ça se tient']:['À surveiller','Peut surprendre','Équilibre à confirmer'];const seed=String(team?.id||team?.name||'').split('').reduce((a,c)=>a+c.charCodeAt(0),0);return pool[seed%pool.length]}
function teamGuestCount(team){try{const ids=(S.teamPlayers||[]).filter(tp=>String(tp.team_id)===String(team.id)).map(tp=>String(tp.player_id));return (S.players||[]).filter(p=>ids.includes(String(p.id))&&p.is_group_member===false).length}catch(_){return 0}}
function enhanceTeams(){if(typeof S==='undefined'||!Array.isArray(S.teams))return;document.querySelectorAll('.swe-team-card').forEach((card,i)=>{const team=S.teams[i]||S.teams.find(t=>card.textContent.includes(t.name));if(!team)return;const head=card.querySelector('.swe-team-card-head');if(head){head.querySelectorAll('b').forEach(b=>{if(b.textContent.trim().startsWith('👕'))b.textContent=b.textContent.replace(/^👕\s*/,'')});}
 const guests=teamGuestCount(team),score=(S.teamBalanceScores||[]).find(x=>String(x.team_id)===String(team.id));const badge=card.querySelector('.chien-boul-badge');const mention=card.querySelector('.team-mention');if(badge&&score){badge.textContent=guests>2?'🐶⚽ Note équipe évaluée par Chien Boul Academy : ??':'🐶⚽ Note équipe évaluée par Chien Boul Academy : '+Number(score.team_score||0).toFixed(1)+'/5';}if(mention&&score)mention.textContent=stableMention(team,score.team_score,guests);
 if(typeof isAdmin==='function'&&isAdmin()&&head&&!head.querySelector('[data-quick-team-color]')){const box=document.createElement('div');box.style.cssText='display:flex;gap:6px;align-items:center;flex-wrap:wrap';const sel=document.createElement('select');sel.dataset.quickTeamColor=team.id;sel.style.cssText='max-width:125px;padding:6px 8px';sel.innerHTML=COLOR_OPTS.map(([v,l])=>'<option value="'+v+'" '+(String(team.color||'').toLowerCase()===v?'selected':'')+'>'+l+'</option>').join('');const btn=document.createElement('button');btn.type='button';btn.textContent='Couleur';btn.style.padding='6px 9px';btn.onclick=async e=>{e.stopPropagation();btn.disabled=true;const r=await sb.rpc('admin_update_team_color',{p_team_id:team.id,p_color:sel.value});btn.disabled=false;if(r.error)return toast(r.error.message);team.color=sel.value;renderTeams();toast('Couleur mise à jour ✅')};box.append(sel,btn);head.appendChild(box)}
 card.querySelectorAll('.player').forEach(row=>{[...row.querySelectorAll('*')].forEach(el=>{const txt=el.textContent||'';if((txt.includes('/5')||txt.includes('Moyenne')||txt.includes('Verdict'))&&!el.children.length){el.style.display='block';el.style.marginTop='4px';el.style.lineHeight='1.25'}})});
 });
 document.querySelectorAll('.public-team-card').forEach(card=>{card.querySelectorAll('.public-team-head').forEach(h=>{h.innerHTML=h.innerHTML.replace(/👕\s*/g,'')});const guestCount=[...card.querySelectorAll('.guest-badge,.guest-tag')].filter(x=>/guest/i.test(x.textContent)).length;if(guestCount>2){[...card.querySelectorAll('*')].filter(el=>!el.children.length&&/Note équipe évaluée par Chien Boul Academy/i.test(el.textContent)).forEach(el=>el.textContent='🐶⚽ Note équipe évaluée par Chien Boul Academy : ??')}})}
function splitMatchPlayers(){document.querySelectorAll('.player').forEach(wrap=>{const head=[...wrap.querySelectorAll('b')].find(b=>b.textContent.includes('Joueurs de ce match'));if(!head||wrap.dataset.sweSplit==='1')return;const rows=[...wrap.querySelectorAll('.row.small')].filter(r=>r.querySelector('select'));if(!rows.length)return;wrap.dataset.sweSplit='1';head.textContent='🔄 Joueurs des 2 équipes';const desc=head.parentElement?.querySelector('.muted');if(desc)desc.textContent='Uniquement les joueurs appartenant aux deux équipes de ce match.';const list=rows[0].parentElement;const starters=document.createElement('div');const subs=document.createElement('details');subs.open=false;subs.style.marginTop='10px';subs.innerHTML='<summary style="cursor:pointer;font-weight:900">🟠 Remplaçants du tournoi</summary><div data-swe-subs style="margin-top:6px"></div>';const subBox=subs.querySelector('[data-swe-subs]');rows.forEach(r=>{const sel=r.querySelector('select');(sel&&sel.value?starters:subBox).appendChild(r)});list.innerHTML='';list.appendChild(starters);if(subBox.children.length)list.appendChild(subs)})}
function fixTournamentLinks(){const card=document.getElementById('sweTournamentLinksCard');if(!card)return;card.querySelectorAll('a.button').forEach(a=>{if(a.dataset.fixed31)return;a.dataset.fixed31='1';a.style.cssText='display:inline-flex;align-items:center;justify-content:center;padding:10px 13px;border-radius:12px;border:1px solid #d9e4de;background:#eef3f0;color:#071b12;font-weight:800;text-decoration:none;white-space:nowrap';a.addEventListener('click',e=>{const href=a.getAttribute('href');if(!href||href==='#'){e.preventDefault();return}e.preventDefault();location.href=href})});}
let injuryLoaded=false,injuryBusy=false;
async function ensureInjuryCard(){const dash=document.getElementById('myPlayerDashboard'),view=document.getElementById('view-myplayer');if(!dash||dash.classList.contains('hidden')||!view?.classList.contains('active')||injuryBusy)return;let card=document.getElementById('sweInjuryCard');if(!card){card=document.createElement('div');card.id='sweInjuryCard';card.className='card';card.style.border='1px solid #f0c6c6';dash.insertAdjacentElement('afterbegin',card)}if(injuryLoaded)return;injuryBusy=true;const r=await sb.rpc('get_my_player_unavailability');injuryBusy=false;const st=r.error?null:r.data;const today=new Date().toISOString().slice(0,10);card.innerHTML='<h2 class="sectiontitle">🩹 Mon indisponibilité</h2><p class="muted">Déclare une blessure ou une période d’absence pour informer tes organisateurs.</p>'+(st?'<div class="player" style="background:#fff5f5"><b>Indisponible'+(st.reason==='injury'?' • Blessure':'')+'</b><div class="muted">Du '+esc31(st.unavailable_from)+(st.unavailable_until?' au '+esc31(st.unavailable_until):' • durée indéterminée')+(st.note?' • '+esc31(st.note):'')+'</div></div>':'')+'<div class="grid g2" style="margin-top:10px"><label><span class="muted">Début</span><input id="sweUnavailableFrom" type="date" value="'+esc31(st?.unavailable_from||today)+'"></label><label><span class="muted">Jusqu’au</span><input id="sweUnavailableUntil" type="date" value="'+esc31(st?.unavailable_until||'')+'"></label></div><div class="grid g2" style="margin-top:8px"><select id="sweUnavailableReason"><option value="injury">🩹 Blessure</option><option value="personal">Indisponibilité personnelle</option><option value="other">Autre</option></select><input id="sweUnavailableNote" maxlength="120" placeholder="Précision facultative" value="'+esc31(st?.note||'')+'"></div><div class="row" style="margin-top:9px"><button id="sweSaveUnavailable" class="primary">Enregistrer</button>'+(st?'<button id="sweClearUnavailable">Je suis de nouveau disponible</button>':'')+'</div>';if(st)card.querySelector('#sweUnavailableReason').value=st.reason||'injury';card.querySelector('#sweSaveUnavailable').onclick=async()=>{const from=card.querySelector('#sweUnavailableFrom').value,until=card.querySelector('#sweUnavailableUntil').value||null,reason=card.querySelector('#sweUnavailableReason').value,note=card.querySelector('#sweUnavailableNote').value.trim();const q=await sb.rpc('set_my_player_unavailability',{p_unavailable_from:from,p_unavailable_until:until,p_reason:reason,p_note:note||null});if(q.error)return toast(q.error.message);injuryLoaded=false;toast('Indisponibilité enregistrée ✅');ensureInjuryCard()};card.querySelector('#sweClearUnavailable')?.addEventListener('click',async()=>{const q=await sb.rpc('clear_my_player_unavailability');if(q.error)return toast(q.error.message);injuryLoaded=false;toast('Tu es de nouveau disponible ✅');ensureInjuryCard()});injuryLoaded=true}
function tick31(){setVersion31();enhanceTeams();splitMatchPlayers();fixTournamentLinks();ensureInjuryCard();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tick31,{once:true});else tick31();document.addEventListener('swe:rendered',tick31);
})();
