(()=>{
  'use strict';

  const VERSION=(window.SWE_BUILD_VERSION||'42.50');
  const STYLE_ID='swe-v4227-hotfix-style';
  const QUEUE_KEY='swe_offline_queue_v1';
  const SNAP_KEY='swe_offline_snapshot_v1';
  let activityMap=new Map();
  let syncing=false;
  let networkDown=false;

  const css=`
/* V42.24 + V42.27 — mobile, notes, équipes publiques et mode terrain */
.swe-substitutes-card{margin-top:12px}.swe-substitutes-card>summary{cursor:pointer;list-style:none}.swe-substitutes-card>summary::-webkit-details-marker{display:none}.swe-substitutes-head span:first-child{display:flex;flex-direction:column;gap:2px}.swe-substitutes-head small{font-size:11px;font-weight:600;opacity:.78}.swe-substitutes-chevron{font-size:22px;line-height:1;transition:transform .18s ease}.swe-substitutes-card[open] .swe-substitutes-chevron{transform:rotate(180deg)}
.match-scoring-first{margin-top:10px;padding:12px;border:2px solid #dfe8e3;border-radius:14px;background:#fff}.match-scoring-title{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:9px}.match-scoring-title span{font-size:12px;color:#69766f}.match-goal-form{margin-bottom:8px}.match-goal-add{width:100%;margin-bottom:7px}.match-goal-history{border-top:1px solid #edf1ef;padding-top:7px}.match-goal-history .row{padding:4px 0}
.match-ratings-card{margin-top:12px;border:1px solid #dce6e1;border-radius:12px;overflow:hidden;background:#fff}.match-ratings-title{font-weight:800;padding:10px 12px;background:#f6f9f7;border-bottom:1px solid #e6ede9}.match-ratings-table{width:100%}.match-ratings-head,.match-ratings-row{display:grid;grid-template-columns:minmax(120px,1fr) 72px 44px 36px 36px;gap:8px;align-items:center;padding:7px 12px}.match-ratings-head{font-size:11px;font-weight:800;color:#718078;background:#fbfcfb}.match-ratings-row{border-top:1px solid #edf2ef;font-size:13px}.match-ratings-row>span:not(.match-rating-name),.match-ratings-row>strong{text-align:center}.match-rating-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.match-ratings-row strong{font-variant-numeric:tabular-nums}
.swe-offline-banner{max-width:1100px;margin:10px auto 0;padding:10px 14px;border-radius:14px;border:1px solid #f2c96d;background:#fff8df;color:#6f4b00;display:flex;align-items:center;justify-content:space-between;gap:12px}.swe-offline-banner b{white-space:nowrap}.swe-offline-banner span{font-size:12px}.swe-offline-banner.online-pending{border-color:#9dc7ff;background:#eef6ff;color:#174a7a}
.swe-player-activity-tools{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;flex-wrap:wrap;margin:0 0 12px;padding:10px 12px;border:1px solid #e2e8e4;border-radius:14px;background:#fafcfb}.swe-player-activity-tools label{min-width:250px;flex:0 1 360px}.swe-player-activity-tools select{margin-top:5px}.swe-activity-meta{margin-top:2px;font-size:11px;color:#7a6b45}.chien-boul-public{margin:10px 12px 0!important;padding:10px 12px;border-radius:12px;background:#fff4c8!important;border:1px solid #f0d56f;color:#714800}.public-team-fun-comment{margin:8px 12px 0;padding:8px 10px;border-radius:11px;background:#f7f2ff;border:1px dashed #c7a8f3;color:#5b3a87;font-size:12px;font-weight:700;line-height:1.4}
@media(max-width:700px){.match-ratings-head,.match-ratings-row{grid-template-columns:minmax(105px,1fr) 66px 38px 30px 30px;padding-left:9px;padding-right:9px;gap:4px}.match-scoring-title{align-items:flex-start;flex-direction:column;gap:2px}.match-goal-form,.match .grid.g3{grid-template-columns:1fr!important}.match-goal-add{margin-top:0}.match button{min-height:42px}.swe-offline-banner{align-items:flex-start;flex-direction:column}.swe-offline-banner b{white-space:normal}.swe-player-activity-tools{align-items:stretch;flex-direction:column}.swe-player-activity-tools label{min-width:0;width:100%;flex:auto}.swe-player-activity-tools select{width:100%}.public-team-card{min-width:0}.chien-boul-public,.public-team-fun-comment{margin-left:9px!important;margin-right:9px!important}}
`;

  function installStyle(){if(document.getElementById(STYLE_ID))return;const x=document.createElement('style');x.id=STYLE_ID;x.textContent=css;document.head.appendChild(x)}
  function setVersion(){window.SWEApplyBuild?.();}
  function uid(){return crypto?.randomUUID?crypto.randomUUID():'00000000-0000-4000-8000-'+Math.random().toString(16).slice(2).padEnd(12,'0').slice(0,12)}
  function qget(){try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]')||[]}catch(_){return []}}
  function qset(rows){localStorage.setItem(QUEUE_KEY,JSON.stringify(rows||[]));renderOfflineBanner()}
  function offlineMode(){return !navigator.onLine||networkDown}
  function queue(type,payload){const rows=qget();rows.push({id:uid(),type,payload,user_id:S?.session?.user?.id||null,workspace_id:S?.workspace?.id||null,created_at:new Date().toISOString()});qset(rows);cacheSnapshot()}

  function ensureBanner(){let b=document.getElementById('sweOfflineBanner');if(b)return b;const anchor=document.getElementById('organizerAccessBanner')||document.querySelector('#main .top');if(!anchor)return null;b=document.createElement('div');b.id='sweOfflineBanner';b.className='swe-offline-banner hidden';b.setAttribute('role','status');b.setAttribute('aria-live','polite');anchor.insertAdjacentElement('afterend',b);return b}
  function renderOfflineBanner(){const b=ensureBanner();if(!b)return;const rows=qget().filter(x=>!S?.workspace?.id||String(x.workspace_id)===String(S.workspace.id));if(!offlineMode()&&!rows.length){b.classList.add('hidden');return}b.classList.remove('hidden');b.classList.toggle('online-pending',!offlineMode()&&rows.length>0);b.innerHTML=offlineMode()?'<b>📴 Mode terrain hors connexion</b><span>'+rows.length+' action'+(rows.length>1?'s':'')+' conservée'+(rows.length>1?'s':'')+' sur ce téléphone. Matchs, scores et buts seront synchronisés automatiquement.</span>':'<b>🔄 Synchronisation en attente</b><span>'+rows.length+' action'+(rows.length>1?'s':'')+' à envoyer.</span>'}

  function cacheSnapshot(){try{if(!S?.session?.user?.id||!S?.workspace?.id)return;localStorage.setItem(SNAP_KEY,JSON.stringify({saved_at:new Date().toISOString(),user_id:S.session.user.id,workspace:S.workspace,workspaceFeatures:S.workspaceFeatures,myPermissions:S.myPermissions,players:S.players,tournaments:S.tournaments,activeTour:S.activeTour,tPlayers:S.tPlayers,teams:S.teams,teamPlayers:S.teamPlayers,matches:S.matches,goals:S.goals,matchAssignments:S.matchAssignments,sportsComplexes:S.sportsComplexes,sportsPitches:S.sportsPitches,teamBalanceScores:S.teamBalanceScores}))}catch(_){}}
  function restoreSnapshot(){try{const z=JSON.parse(localStorage.getItem(SNAP_KEY)||'null');if(!z||!S?.session?.user?.id||String(z.user_id)!==String(S.session.user.id))return false;S.workspace=z.workspace||S.workspace;S.workspaceFeatures={...S.workspaceFeatures,...(z.workspaceFeatures||{})};S.myPermissions={...S.myPermissions,...(z.myPermissions||{})};['players','tournaments','tPlayers','teams','teamPlayers','matches','goals','matchAssignments','sportsComplexes','sportsPitches','teamBalanceScores'].forEach(k=>S[k]=z[k]||[]);S.activeTour=z.activeTour||S.activeTour;if(S.workspace){localStorage.setItem('swe_workspace_id',S.workspace.id);document.getElementById('workspaceSetup')?.classList.add('hidden');document.getElementById('accountOnboarding')?.classList.add('hidden');const n=document.getElementById('workspaceName');if(n)n.textContent=S.workspace.name+' • Mode hors connexion';try{renderWorkspaceSwitcher();applyPermissions();renderAll()}catch(_){}renderOfflineBanner();return true}}catch(e){console.warn('restore offline',e)}return false}

  async function syncQueue(){if(syncing||offlineMode()||!S?.session)return;const rows=qget();if(!rows.length)return renderOfflineBanner();syncing=true;const remain=[];let sent=0;for(let i=0;i<rows.length;i++){const op=rows[i];if(op.user_id&&String(op.user_id)!==String(S.session.user.id)){remain.push(op);continue}try{let r={error:null},x=op.payload||{};if(op.type==='insert_match')r=await sb.from('matches').insert(x.row);else if(op.type==='update_match_score')r=await sb.from('matches').update(x.patch).eq('id',x.match_id);else if(op.type==='insert_goal')r=await sb.from('goals').insert(x.row);else if(op.type==='delete_goal')r=await sb.from('goals').delete().eq('id',x.goal_id);if(r.error)throw r.error;sent++}catch(e){remain.push(op,...rows.slice(i+1));networkDown=true;break}}qset(remain);syncing=false;if(!remain.length){networkDown=false;if(sent)toast('✅ '+sent+' action'+(sent>1?'s':'')+' terrain synchronisée'+(sent>1?'s':'')+'.');try{await loadTournament();renderAll()}catch(_){}}renderOfflineBanner()}

  function foldSubstitutes(){document.querySelectorAll('.swe-substitutes-card:not(details)').forEach(card=>{const head=card.querySelector('.swe-substitutes-head'),list=card.querySelector('.swe-substitutes-list');if(!head||!list)return;const count=list.children.length,details=document.createElement('details'),summary=document.createElement('summary');details.className=card.className;summary.className='swe-substitutes-head';summary.innerHTML='<span><b>🟠 Remplaçants communs</b><small>'+count+' joueur'+(count>1?'s':'')+' • toucher pour afficher</small></span><span class="swe-substitutes-chevron">⌄</span>';details.append(summary,list.cloneNode(true));card.replaceWith(details)})}
  function formatRatings(){document.querySelectorAll('.card.match').forEach(match=>{match.querySelectorAll('b').forEach(title=>{if(title.textContent.trim()!=='⭐ Notes des joueurs')return;const notes=title.parentElement;if(!notes||notes.classList.contains('match-ratings-card'))return;const source=notes.querySelector('.muted');if(!source)return;const lines=source.innerHTML.split(/<br\s*\/?\s*>/i).map(x=>x.trim()).filter(Boolean),rows=[];for(const line of lines){const t=document.createElement('div');t.innerHTML=line;const m=t.textContent.trim().match(/^(.*?)\s+([0-9]+(?:[.,][0-9]+)?\/10)\s+\((.*?)\s+•\s+⚽\s*(\d+)\s+•\s+🎯\s*(\d+)\)$/);if(m)rows.push({name:m[1],note:m[2].replace(',','.'),result:m[3],goals:m[4],assists:m[5]})}if(!rows.length)return;notes.className='match-ratings-card';notes.removeAttribute('style');notes.innerHTML='<div class="match-ratings-title">⭐ Notes des joueurs</div><div class="match-ratings-table"><div class="match-ratings-head"><span>Joueur</span><span>Note</span><span>Rés.</span><span>⚽</span><span>🎯</span></div>'+rows.map(r=>'<div class="match-ratings-row"><span class="match-rating-name">'+esc(r.name)+'</span><strong>'+r.note+'</strong><span>'+esc(r.result)+'</span><span>'+r.goals+'</span><span>'+r.assists+'</span></div>').join('')+'</div>'})})}
  function moveScoringFirst(){document.querySelectorAll('.card.match').forEach(match=>{if(match.querySelector(':scope > .match-scoring-first'))return;const add=[...match.querySelectorAll(':scope > button')].find(b=>b.textContent.trim()==='+ But');if(!add)return;const form=add.previousElementSibling,hist=add.nextElementSibling;if(!form||!form.matches('.grid.g3')||!hist)return;const wrap=document.createElement('div');wrap.className='match-scoring-first';const title=document.createElement('div');title.className='match-scoring-title';title.innerHTML='<b>⚽ Saisir un but / une passe</b><span>Action rapide pendant le match</span>';form.classList.add('match-goal-form');add.classList.add('match-goal-add');hist.classList.add('match-goal-history');hist.style.marginTop='';wrap.append(title,form,add,hist);match.insertBefore(wrap,match.children[2]||null)})}

  function enhancePublicTeams(){const root=document.getElementById('publicTeams');if(!root)return;root.querySelectorAll('.public-team-card').forEach(card=>{card.querySelector('.public-team-average')?.classList.add('chien-boul-public');if(card.querySelector('.public-team-fun-comment'))return;const guests=card.querySelectorAll('.guest-badge').length;if(!guests)return;const name=card.querySelector('.public-team-head')?.textContent||card.textContent;let h=0;for(const c of name)h=(h*31+c.charCodeAt(0))>>>0;const one=['👀 Guest à jauger : potentiel surprise, adversaires prévenus.','🕵️ Un guest à évaluer : joueur à surveiller 😏','🎲 Guest encore mystérieux : la Chien Boul Academy demande confirmation terrain.'];const many=['🕵️ '+guests+' guests à jauger : équipe mystère, méfiance 😏','👀 '+guests+' guests encore sans verdict complet : ça peut piquer.','🎲 '+guests+' inconnues dans l’équation : Chien Boul Academy garde un œil dessus.'];const d=document.createElement('div');d.className='public-team-fun-comment';d.textContent=(guests>1?many:one)[h%(guests>1?many.length:one.length)];const avg=card.querySelector('.public-team-average');(avg||card.querySelector('.public-team-head'))?.insertAdjacentElement('afterend',d)})}

  function activityDays(a){if(!a?.last_swe_date)return Infinity;return Math.max(0,Math.floor((Date.now()-new Date(a.last_swe_date+'T12:00:00').getTime())/86400000))}
  function activityLabel(a){const n=Number(a?.swe_count||0);if(!n||!a?.last_swe_date)return 'Jamais participé à un Swé enregistré';const d=activityDays(a);return 'Dernier Swé : '+new Date(a.last_swe_date+'T12:00:00').toLocaleDateString('fr-FR')+' • '+n+' participation'+(n>1?'s':'')+(d>=30?' • '+d+' j sans jouer':'')}
  async function loadActivity(){if(!S?.workspace?.id||!isAdmin())return;const r=await sb.rpc('get_workspace_player_activity',{p_workspace_id:S.workspace.id});if(!r.error)activityMap=new Map((r.data||[]).map(x=>[String(x.player_id),x]))}
  function enhancePlayers(){if(!isAdmin())return;const box=document.getElementById('playersList');if(!box)return;let tools=document.getElementById('swePlayerActivityTools');if(!tools){tools=document.createElement('div');tools.id='swePlayerActivityTools';tools.className='swe-player-activity-tools';tools.innerHTML='<label><span class="muted">🕒 Activité des joueurs</span><select id="swePlayerActivityFilter"><option value="all">Tous les joueurs</option><option value="inactive_30">Inactifs depuis 30 jours ou +</option><option value="inactive_60">Inactifs depuis 60 jours ou +</option><option value="inactive_90">Inactifs depuis 90 jours ou +</option><option value="never">Jamais participé à un Swé</option></select></label><div id="swePlayerActivitySummary" class="muted"></div>';box.parentElement.insertBefore(tools,box);tools.querySelector('select').addEventListener('change',applyActivityFilter)}const cards=[...box.children].filter(x=>x.classList.contains('player'));cards.forEach((card,i)=>{const pl=S.players?.[i];if(!pl)return;card.dataset.playerId=pl.id;const a=activityMap.get(String(pl.id));const meta=card.querySelector('.muted');if(meta&&!card.querySelector('.swe-activity-meta')){const x=document.createElement('div');x.className='swe-activity-meta';x.textContent='🕒 '+activityLabel(a);meta.insertAdjacentElement('afterend',x)}});applyActivityFilter()}
  function applyActivityFilter(){const sel=document.getElementById('swePlayerActivityFilter'),box=document.getElementById('playersList');if(!sel||!box)return;const v=sel.value;let shown=0;[...box.children].filter(x=>x.classList.contains('player')).forEach(card=>{const a=activityMap.get(String(card.dataset.playerId)),never=Number(a?.swe_count||0)===0,days=activityDays(a);let ok=v==='all'||(v==='never'&&never)||(v.startsWith('inactive_')&&days>=Number(v.split('_')[1]||0));card.style.display=ok?'':'none';if(ok)shown++});const out=document.getElementById('swePlayerActivitySummary');if(out)out.textContent=shown+' joueur'+(shown>1?'s':'')+' affiché'+(shown>1?'s':'')+' sur '+(S.players?.length||0)}

  function matchFromCard(card){const cards=[...document.querySelectorAll('#matchesList .card.match')],idx=cards.indexOf(card);return idx>=0?S.matches?.[idx]:null}
  document.addEventListener('click',e=>{if(!offlineMode())return;const b=e.target.closest('button');if(!b)return;
    if(b.id==='addMatch'){e.preventDefault();e.stopImmediatePropagation();const t=currentTour(),home=document.getElementById('homeTeam')?.value,away=document.getElementById('awayTeam')?.value,pitch=document.getElementById('pitch')?.value;if(!t||!home||!away||home===away)return toast('Choisis deux équipes différentes');if(t.format==='league'&&!pitch)return toast('Pour un match de Ligue, indique obligatoirement le terrain.');const row={id:uid(),tournament_id:t.id,home_team_id:home,away_team_id:away,match_order:(S.matches?.length||0)+1,pitch:pitch||null,round_label:document.getElementById('roundLabel')?.value.trim()||null,home_score:0,away_score:0,status:'scheduled'};queue('insert_match',{row});S.matches.push(row);renderMatches();toast('📴 Match créé sur ce téléphone.');return}
    if(b.id==='roundRobin'){e.preventDefault();e.stopImmediatePropagation();const t=currentTour();if(!t||S.teams.length<2)return toast('Crée les équipes d’abord');if(t.format==='league')return toast('En Ligue, crée les matchs un par un.');const existing=new Set(S.matches.map(m=>[m.home_team_id,m.away_team_id].sort().join('|'))),rows=[];let n=S.matches.length+1;for(let i=0;i<S.teams.length;i++)for(let j=i+1;j<S.teams.length;j++){const key=[S.teams[i].id,S.teams[j].id].sort().join('|');if(!existing.has(key))rows.push({id:uid(),tournament_id:t.id,home_team_id:S.teams[i].id,away_team_id:S.teams[j].id,match_order:n++,home_score:0,away_score:0,status:'scheduled'})}rows.forEach(row=>queue('insert_match',{row}));S.matches.push(...rows);renderMatches();toast('📴 '+rows.length+' matchs créés hors connexion.');return}
    const card=b.closest('.card.match'),m=card?matchFromCard(card):null;if(!m)return;
    if(b.textContent.trim()==='💾 Score'){e.preventDefault();e.stopImmediatePropagation();const inputs=[...b.parentElement.querySelectorAll('input[type="number"]')];const patch={home_score:Math.max(0,Number(inputs[0]?.value)||0),away_score:Math.max(0,Number(inputs[1]?.value)||0),status:'finished',finished_at:new Date().toISOString()};queue('update_match_score',{match_id:m.id,patch});Object.assign(m,patch);renderMatches();toast('📴 Résultat enregistré sur ce téléphone.');return}
    if(b.textContent.trim()==='+ But'){e.preventDefault();e.stopImmediatePropagation();const scope=b.closest('.match-scoring-first')||card,selects=[...scope.querySelectorAll('select')];const team=selects[0]?.value,scorer=selects[1]?.value,assister=selects[2]?.value;if(!scorer)return toast('Choisis le buteur');if(assister===scorer)return toast('Buteur et passeur différents');const row={id:uid(),match_id:m.id,team_id:team,scorer_player_id:scorer,assister_player_id:assister||null,created_at:new Date().toISOString()};queue('insert_goal',{row});S.goals.push(row);renderMatches();toast('📴 But enregistré sur ce téléphone.');return}
    if(b.textContent.trim()==='Annuler'&&b.closest('.match-goal-history')){e.preventDefault();e.stopImmediatePropagation();const buttons=[...card.querySelectorAll('.match-goal-history button')].filter(x=>x.textContent.trim()==='Annuler'),idx=buttons.indexOf(b),goals=(S.goals||[]).filter(g=>String(g.match_id)===String(m.id));const g=goals[idx];if(!g)return;queue('delete_goal',{goal_id:g.id});S.goals=S.goals.filter(x=>String(x.id)!==String(g.id));renderMatches();toast('📴 But annulé sur ce téléphone.');}
  },true);

  const nativeFetch=window.fetch.bind(window);window.fetch=async(...args)=>{try{const r=await nativeFetch(...args);if(r.ok)networkDown=false;return r}catch(e){networkDown=true;renderOfflineBanner();throw e}};
  window.addEventListener('online',()=>{networkDown=false;renderOfflineBanner();setTimeout(syncQueue,300)});window.addEventListener('offline',()=>{networkDown=true;renderOfflineBanner()});

  try{const originalRenderPlayers=renderPlayers;renderPlayers=function(...a){const r=originalRenderPlayers.apply(this,a);setTimeout(enhancePlayers,0);return r}}catch(_){ }
  try{const originalLoadAll=loadAll;loadAll=async function(...a){if(offlineMode()&&restoreSnapshot())return;const r=await originalLoadAll.apply(this,a);if(!offlineMode()){await loadActivity();cacheSnapshot()}return r}}catch(_){ }
  try{const originalLoadTournament=loadTournament;loadTournament=async function(...a){if(offlineMode()&&restoreSnapshot())return;const r=await originalLoadTournament.apply(this,a);if(!offlineMode())cacheSnapshot();return r}}catch(_){ }
  try{const originalBoot=boot;boot=async function(...a){if(offlineMode()&&restoreSnapshot()){renderOfflineBanner();return}return originalBoot.apply(this,a)}}catch(_){ }

  let scheduled=false;function apply(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;installStyle();setVersion();foldSubstitutes();moveScoringFirst();formatRatings();enhancePublicTeams();enhancePlayers();renderOfflineBanner()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{apply();setTimeout(()=>{loadActivity().then(enhancePlayers);syncQueue()},600)},{once:true});else{apply();setTimeout(()=>{loadActivity().then(enhancePlayers);syncQueue()},600)}
  document.addEventListener('swe:rendered',apply);
})();
