(()=>{
'use strict';
const {createClient}=window.supabase;
const sb=createClient('https://fbppesfxkvledwjemwsn.supabase.co','sb_publishable_Kl3HDD4S08YC1EB-cWJKaQ_e9gCbygp',{global:{fetch:(input,init={})=>fetch(input,{...init,cache:'no-store'})}});
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const params=new URLSearchParams(location.search);
let token=params.get('public')||null;
let tournamentId=params.get('tournament')||null;
let timer=null,busy=false;
function setStatus(text,ok=true){$('#liveStatus').textContent=text;const dot=document.querySelector('.live-dot');if(dot)dot.style.background=ok?'#4ade80':'#fb923c'}
function teamColor(t){const n=String(t?.name||'').toLowerCase();return t?.color||(/noir/.test(n)?'#111827':/bleu/.test(n)?'#2563eb':/rouge/.test(n)?'#dc2626':/vert/.test(n)?'#16a34a':/blanc|rocket/.test(n)?'#f8fafc':'#64748b')}
function teamFg(bg){return ['#111827','#2563eb','#dc2626','#16a34a','#64748b'].includes(String(bg).toLowerCase())?'#fff':'#111827'}
function teamNote(t){const n=Number(t?.coorg_team_score||0)>0?Number(t.coorg_team_score):Number(t?.team_score||0);return n>0?n:null}
function funComment(n){if(!n)return '';return n===1?'🕵️ Guest à évaluer : joueur à surveiller 😏':'👀 '+n+' guests à jauger : équipe mystère, méfiance 😏'}
async function resolve(){const s=params.get('s');if(!s||token&&tournamentId)return;const r=await sb.rpc('resolve_public_tournament_short_link',{p_code:s});if(r.error)throw r.error;if(!r.data?.public_token||!r.data?.tournament_id)throw new Error('Lien Live invalide.');token=r.data.public_token;tournamentId=r.data.tournament_id}
function render(data){const tour=(data.tournaments||[]).find(t=>String(t.id)===String(tournamentId));if(!tour)throw new Error('Ce tournoi est introuvable.');$('#liveTitle').textContent=(tour.name||'Tournoi SWÉ')+(tour.tournament_date?' • '+tour.tournament_date:'');const teams=(data.teams||[]).filter(t=>String(t.tournament_id)===String(tournamentId));const teamIds=new Set(teams.map(t=>String(t.id)));const teamPlayers=(data.team_players||[]).filter(tp=>teamIds.has(String(tp.team_id)));const regs=(data.tournament_players||[]).filter(r=>String(r.tournament_id)===String(tournamentId));const players=new Map((data.players||[]).map(p=>[String(p.id),p]));const teamMap=new Map(teams.map(t=>[String(t.id),t]));const assigned=new Set(teamPlayers.map(tp=>String(tp.player_id)));
$('#liveTeams').innerHTML=teams.length?teams.map(t=>{const bg=teamColor(t),members=teamPlayers.filter(tp=>String(tp.team_id)===String(t.id)).map(tp=>players.get(String(tp.player_id))).filter(Boolean),guests=members.filter(p=>p.is_group_member===false).length,note=teamNote(t);return '<article class="live-team"><div class="live-team-head" style="background:'+bg+';color:'+teamFg(bg)+'">👕 '+esc(t.name)+'</div><div class="live-team-body">'+(note?'<div class="live-note">🐶⚽ <b>Note équipe évaluée par Chien Boul Academy : '+note.toFixed(1)+'/5</b>'+(t.mention?' • '+esc(t.mention):'')+'</div>':'')+(guests?'<div class="muted" style="margin-bottom:8px">'+funComment(guests)+'</div>':'')+members.map(p=>'<div class="live-player">'+esc(p.name)+(p.is_group_member===false?' <span class="guest-tag">Guest</span>':'')+'</div>').join('')+'</div></article>'}).join(''):'<p class="muted">Les équipes ne sont pas encore publiées.</p>';
const subs=regs.filter(r=>r.present&&r.is_substitute&&r.registration_status!=='waitlist'&&!assigned.has(String(r.player_id))).map(r=>players.get(String(r.player_id))).filter(Boolean);$('#liveSubs').innerHTML=subs.length?'<details class="live-subs" style="margin-top:12px"><summary>🟠 Remplaçants communs • '+subs.length+'</summary><div style="margin-top:8px">'+subs.map(p=>'<span class="guest-badge" style="margin:3px">'+esc(p.name)+'</span>').join('')+'</div></details>':'';
const matches=(data.matches||[]).filter(m=>String(m.tournament_id)===String(tournamentId)).sort((a,b)=>(a.match_order||0)-(b.match_order||0));const played=matches.filter(m=>m.finished_at||m.started_at||m.status==='finished'||m.status==='started'||Number(m.home_score)||Number(m.away_score));const rows=teams.map(t=>({id:String(t.id),name:t.name,mj:0,v:0,n:0,d:0,bp:0,bc:0,pts:0})),map=new Map(rows.map(r=>[r.id,r]));played.forEach(m=>{const h=map.get(String(m.home_team_id)),a=map.get(String(m.away_team_id));if(!h||!a)return;const hs=Number(m.home_score||0),as=Number(m.away_score||0);h.mj++;a.mj++;h.bp+=hs;h.bc+=as;a.bp+=as;a.bc+=hs;if(hs>as){h.v++;a.d++;h.pts+=3}else if(as>hs){a.v++;h.d++;a.pts+=3}else{h.n++;a.n++;h.pts++;a.pts++}});rows.sort((a,b)=>b.pts-a.pts||(b.bp-b.bc)-(a.bp-a.bc)||b.bp-a.bp||a.name.localeCompare(b.name));$('#liveRanking').innerHTML=rows.length?'<table class="live-table"><thead><tr><th>#</th><th>Équipe</th><th>MJ</th><th>V</th><th>N</th><th>D</th><th>Diff</th><th>Pts</th></tr></thead><tbody>'+rows.map((r,i)=>'<tr><td>'+(i===0?'👑':i+1)+'</td><td><b>'+esc(r.name)+'</b></td><td>'+r.mj+'</td><td>'+r.v+'</td><td>'+r.n+'</td><td>'+r.d+'</td><td>'+((r.bp-r.bc)>=0?'+':'')+(r.bp-r.bc)+'</td><td><b>'+r.pts+'</b></td></tr>').join('')+'</tbody></table>':'<p class="muted">Classement indisponible.</p>';
$('#liveMatches').innerHTML=matches.length?matches.map((m,i)=>{const h=teamMap.get(String(m.home_team_id)),a=teamMap.get(String(m.away_team_id)),st=m.finished_at||m.status==='finished'?'Terminé':m.started_at||m.status==='started'?'En cours':'À jouer';return '<div class="live-match"><div><div class="muted">Match '+(i+1)+(m.pitch?' • '+esc(m.pitch):'')+' • '+st+'</div><b>'+esc(h?.name||'?')+' — '+esc(a?.name||'?')+'</b></div><div class="live-score">'+Number(m.home_score||0)+' - '+Number(m.away_score||0)+'</div></div>'}).join(''):'<p class="muted">Les matchs ne sont pas encore créés.</p>';
const now=new Date();$('#liveUpdated').textContent='Actualisé '+now.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});setStatus(navigator.onLine?'Live connecté • mise à jour toutes les 15 s':'Hors connexion • dernier état affiché',navigator.onLine);}
async function sync(){if(busy)return;busy=true;try{await resolve();if(!token||!tournamentId)throw new Error('Paramètres du lien Live incomplets.');const r=await sb.rpc('get_public_workspace_snapshot_v2',{p_token:token});if(r.error)throw r.error;render(r.data||{});$('#liveError').classList.add('hidden')}catch(e){$('#liveError').textContent=e.message||'Impossible de charger le tournoi.';$('#liveError').classList.remove('hidden');setStatus(navigator.onLine?'Synchronisation impossible':'Hors connexion',false)}finally{busy=false}}
window.addEventListener('online',()=>{setStatus('Connexion retrouvée • synchronisation…',true);sync()});window.addEventListener('offline',()=>setStatus('Hors connexion • dernier état affiché',false));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync()});sync();timer=setInterval(()=>{if(navigator.onLine&&document.visibilityState==='visible')sync()},15000);
})();
