(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const endpoint='https://fbppesfxkvledwjemwsn.supabase.co/rest/v1/rpc/get_public_sales_catalog_v1';
const key='sb_publishable_Kl3HDD4S08YC1EB-cWJKaQ_e9gCbygp';
const features=[['tournaments_enabled','Tournois','Crée et organise tes tournois.'],['league_enabled','Ligues','Retrouve ton groupe au fil des rencontres.'],['rankings_enabled','Classements','Suis les résultats de la saison.'],['player_ratings_enabled','Notes joueurs','Évalue les joueurs avec tes co-gestionnaires.'],['team_review_enabled','Validation des équipes','Recueille les avis avant de valider les équipes.'],['payments_enabled','Suivi des paiements','Suis les participations et les règlements.'],['top_player_enabled','Top Player','Mets en lumière les performances de ton groupe.'],['match_ratings_enabled','Notes de match','Retrouve les évaluations après chaque rencontre.'],['third_half_enabled','3e mi-temps / Glacière','Organise le moment convivial après le match.']];
const money=n=>(Number(n)/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
let catalog=null,inflight=null;
async function load(force=false){if(catalog&&!force)return catalog;if(inflight)return inflight;inflight=(async()=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(endpoint,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:'{}',signal:controller.signal,cache:'no-store'});if(!r.ok)throw new Error('Catalogue indisponible');const data=await r.json();if(!Array.isArray(data.plans)||!Array.isArray(data.modules))throw new Error('Catalogue invalide');catalog=data;return data}finally{clearTimeout(timer);inflight=null}})();return inflight}
function plans(){return (catalog?.plans||[]).filter(p=>['player','standard','pro'].includes(p.code)&&p.active!==false)}
function price(p,annual){return p.is_free?'Gratuit':money(annual?p.annual_price_cents:p.monthly_price_cents)+' / '+(annual?'an':'mois')}
function highlights(p){if(p.code==='player')return ['Rejoins des tournois','Retrouve ton ID SWÉ','Suis ton évolution','Vis ta communauté'];return [`Jusqu’à ${p.max_players} joueurs`,`${p.max_coorganizers} co-gestionnaires`].concat(features.filter(([k])=>p[k]).slice(0,3).map(([,label])=>label))}
function details(code,trigger){document.getElementById('offerDetails')?.remove();const dialog=document.createElement('dialog');dialog.id='offerDetails';dialog.className='offer-dialog';const selected=code?plans().filter(p=>p.code===code):plans().filter(p=>p.code!=='player');dialog.setAttribute('aria-labelledby','offerDetailTitle');const rows=code==='player'?[['Profil joueur','Inclus'],['Rejoindre des tournois','Inclus'],['Statistiques personnelles','Inclus']]:[['Joueurs maximum',...selected.map(p=>p.max_players)],['Co-gestionnaires',...selected.map(p=>p.max_coorganizers)],...features.map(([k,l])=>[l,...selected.map(p=>p[k]?'Inclus':'Non inclus')])];dialog.innerHTML=`<header><h2 id="offerDetailTitle">${code?esc(selected[0]?.name||'La formule'):'Compare les options et modules'}</h2><button class="offer-more" type="button" data-close aria-label="Fermer le détail">✕</button></header><div class="offer-table"><table><thead><tr><th scope="col">Option</th>${selected.map(p=>`<th scope="col">${esc(p.name)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr><th scope="row">${esc(row[0])}</th>${row.slice(1).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${code==='player'?'':`<h3>À quoi servent les modules ?</h3>${features.filter(([k])=>['top_player_enabled','match_ratings_enabled','third_half_enabled','team_review_enabled'].includes(k)).map(([,label,description])=>`<div class="offer-module"><b>${esc(label)}</b><br>${esc(description)}</div>`).join('')}<h3>Options vendues séparément</h3>${catalog.modules.length?catalog.modules.map(m=>`<div class="offer-module"><b>${esc(m.name)}</b> · ${money(m.price_cents)}${m.billing_mode==='monthly'?' / mois':m.billing_mode==='annual'?' / an':' à l’unité'}<br>${esc(m.description||'')}</div>`).join(''):'<p>Aucune offre additionnelle publiée pour le moment.</p>'}`}`;document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{dialog.remove();trigger?.focus()},{once:true});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.showModal()}
function mount(host,{organizer=false,onSelect}={}){if(!host||host.dataset.offerMounted)return;host.dataset.offerMounted='1';host.classList.add('swe-offers');let annual=new URLSearchParams(location.search).get('billing')==='annual',selected='standard';try{annual=annual||localStorage.getItem('swe_selected_billing')==='annual';selected=new URLSearchParams(location.search).get('offer')||localStorage.getItem('swe_selected_offer')||'standard'}catch(_){}let first=true;
 async function render(force=false){host.setAttribute('aria-busy','true');try{await load(force);const entries=plans().filter(p=>!organizer||p.code!=='player');if(!entries.length)throw new Error('Aucune formule disponible');if(!entries.some(p=>p.code===selected))selected=entries[0].code;const current=entries.find(p=>p.code===selected);host.dataset.amount=String(annual?current.annual_price_cents:current.monthly_price_cents);host.innerHTML=`<div class="offer-toolbar"><div class="offer-billing" role="group" aria-label="Période de facturation"><label><input type="radio" name="${organizer?'swe4337Billing':'offerBilling'}" value="monthly" ${annual?'':'checked'}> Mensuel</label><label><input type="radio" name="${organizer?'swe4337Billing':'offerBilling'}" value="annual" ${annual?'checked':''}> Annuel</label></div><button type="button" class="offer-more" data-details="">Détail des options et modules ＋</button></div><div class="offer-grid ${organizer?'organizer':''}">${entries.map(p=>`<article class="offer-card ${p.code==='standard'?'featured':''} ${organizer&&p.code===selected?'selected':''}">${p.code==='standard'?'<span class="offer-badge">★ POUR TON GROUPE</span>':''}<div class="offer-icon" aria-hidden="true">${p.code==='player'?'⚽':p.code==='standard'?'📅':'👑'}</div><h2>${esc(p.name)}</h2><span class="offer-price">${price(p,annual)}</span><p>${esc(p.description||'')}</p><ul>${highlights(p).map(s=>`<li>${esc(s)}</li>`).join('')}</ul>${organizer?`<input type="radio" hidden name="swe4337Plan" value="${esc(p.code)}" ${p.code===selected?'checked':''}>`:''}<button type="button" class="offer-cta" data-choose="${esc(p.code)}" ${organizer?`aria-pressed="${p.code===selected}"`:''}>${organizer&&p.code===selected?'✓ Formule sélectionnée':p.code==='player'?'Je m’inscris →':'Je choisis '+esc(p.name)+' →'}</button><button type="button" class="offer-more" data-details="${esc(p.code)}">Voir tout ce qui est inclus</button></article>`).join('')}</div>${organizer?'<div class="offer-note"><b>60 jours offerts.</b> Carte bancaire demandée, aucun prélèvement aujourd’hui. Sauf résiliation avant la fin de l’essai, la formule choisie démarre automatiquement au 61e jour au tarif affiché.</div>':''}`;
 host.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>details(b.dataset.details,b));host.querySelectorAll('.offer-billing input').forEach(r=>r.onchange=()=>{annual=r.value==='annual';render()});host.querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>{selected=b.dataset.choose;if(organizer){onSelect?.(selected,annual);render();return}if(selected==='player'){location.assign('https://www.swetournament.fr/?signup=1');return}try{localStorage.setItem('swe_selected_offer',selected);localStorage.setItem('swe_offer_setup','1');localStorage.setItem('swe_selected_billing',annual?'annual':'monthly')}catch(_){}location.assign('/?start=player&organizer_setup=1&offer='+encodeURIComponent(selected)+'&billing='+(annual?'annual':'monthly'))});onSelect?.(selected,annual)
 }catch(_){host.innerHTML='<div class="offer-error" role="alert">Les formules sont momentanément indisponibles. <button class="offer-more" type="button">Réessayer</button></div>';host.querySelector('button').onclick=()=>render(true);onSelect?.(null,annual)}finally{host.setAttribute('aria-busy','false')}}render();}
window.SWEOffers={load,mount,details,features};if(document.getElementById('publicOffers'))mount(document.getElementById('publicOffers'));
})();
