(()=>{
'use strict';
const {createClient}=window.supabase;
const sb=createClient('https://fbppesfxkvledwjemwsn.supabase.co','sb_publishable_Kl3HDD4S08YC1EB-cWJKaQ_e9gCbygp',{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'swe-complex-auth-v1'}});
const E=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])),money=c=>((Number(c)||0)/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'}),days=['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
function showLogin(msg=''){E('app').classList.add('hidden');E('login').classList.remove('hidden');E('loginError').textContent=msg}
function showApp(){E('login').classList.add('hidden');E('app').classList.remove('hidden')}
async function load(){const r=await sb.rpc('get_my_complex_partner_dashboard');if(r.error)throw r.error;const cs=Array.isArray(r.data?.complexes)?r.data.complexes:[];if(!cs.length){E('content').innerHTML='<div class="card"><b>Aucun complexe partenaire n’est rattaché à ce compte.</b><div class="muted" style="margin-top:6px">Ton dossier doit être validé par SWÉ avant l’ouverture de l’espace partenaire.</div></div>';return}E('content').innerHTML=cs.map(c=>{
 const slots=Array.isArray(c.slots)?c.slots:[],packs=Array.isArray(c.packages)?c.packages:[],plan=String(c.plan_code||'');
 return '<section class="hero"><div class="status">COMPLEXE PARTENAIRE</div><h1>'+esc(c.name)+'</h1><div>'+esc([c.city,c.address].filter(Boolean).join(' • '))+'</div></section><div class="grid"><div class="card kpi"><span>Formule</span><b>'+esc(plan==='visibility_350'?'Visibilité':'Partenaire SWÉ')+'</b><div class="muted">'+money(c.monthly_fee_cents)+'/mois</div></div><div class="card kpi"><span>Créneaux SWÉ</span><b>'+slots.filter(x=>x.active!==false).length+'</b><div class="muted">créneau(x) actif(s)</div></div><div class="card kpi"><span>Formules / packs</span><b>'+packs.filter(x=>x.active!==false).length+'</b><div class="muted">offre(s) active(s)</div></div></div><div class="card section"><h2 style="margin-top:0">Profil public</h2><label class="field"><span>Accroche</span><input data-tagline="'+esc(c.complex_id)+'" value="'+esc(c.public_tagline||'')+'"></label><label class="field"><span>Description</span><textarea rows="4" data-description="'+esc(c.complex_id)+'">'+esc(c.public_description||'')+'</textarea></label><label class="field"><span>Lien de réservation</span><input data-booking="'+esc(c.complex_id)+'" value="'+esc(c.booking_url||'')+'" placeholder="https://..."></label><button class="primary" data-save="'+esc(c.complex_id)+'">Enregistrer</button></div><div class="grid section"><div class="card"><h2 style="margin-top:0">Créneaux proposés sur SWÉ</h2>'+(slots.length?slots.map(s=>'<div class="slot"><b>'+esc(days[Number(s.weekday)]||'Jour')+' '+String(s.start_time||'').slice(0,5)+'–'+String(s.end_time||'').slice(0,5)+'</b><div class="muted">'+esc(s.duration_minutes)+' min • '+esc(s.pitch_count)+' terrain(s) • prix membre SWÉ '+money(s.swe_public_price_cents)+'</div></div>').join(''):'<div class="muted">Aucun créneau configuré.</div>')+'</div><div class="card"><h2 style="margin-top:0">Packs & formules</h2>'+(packs.length?packs.map(p=>'<div class="pack"><b>'+esc(p.name)+' • '+money(p.public_price_cents)+'</b><div class="muted">'+esc(p.description||'')+'</div></div>').join(''):'<div class="muted">Aucun pack configuré.</div>')+'</div></div><div class="card section"><b>Confidentialité commerciale</b><div class="muted" style="margin-top:6px">Cet espace affiche uniquement les informations utiles au complexe. Les paramètres internes SWÉ, coûts internes et marges de la plateforme ne sont jamais affichés ici.</div></div>'
 }).join('');
 E('content').querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const id=b.dataset.save;b.disabled=true;const r=await sb.rpc('complex_partner_update_public_profile',{p_complex_id:id,p_public_tagline:E('content').querySelector('[data-tagline="'+CSS.escape(id)+'"]').value,p_public_description:E('content').querySelector('[data-description="'+CSS.escape(id)+'"]').value,p_booking_url:E('content').querySelector('[data-booking="'+CSS.escape(id)+'"]').value});b.disabled=false;if(r.error){alert(r.error.message);return}b.textContent='Enregistré ✓';setTimeout(()=>b.textContent='Enregistrer',1200)});
}
async function boot(){const {data}=await sb.auth.getSession();if(data?.session){showApp();try{await load()}catch(e){E('content').innerHTML='<div class="card error">'+esc(e.message||e)+'</div>'}}else showLogin()}
E('loginBtn').onclick=async()=>{E('loginError').textContent='Connexion…';const r=await sb.auth.signInWithPassword({email:E('email').value.trim(),password:E('password').value});if(r.error)return showLogin(r.error.message);showApp();try{await load()}catch(e){showLogin(e.message||String(e))}};E('password').addEventListener('keydown',e=>{if(e.key==='Enter')E('loginBtn').click()});E('logout').onclick=async()=>{await sb.auth.signOut({scope:'local'});showLogin()};boot();
})();