(()=>{
'use strict';
const {createClient}=window.supabase;
const sb=createClient('https://fbppesfxkvledwjemwsn.supabase.co','sb_publishable_Kl3HDD4S08YC1EB-cWJKaQ_e9gCbygp',{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'swe-complex-auth-v1'}});
const E=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])),money=c=>((Number(c)||0)/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'}),days=['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
const dt=v=>{if(!v)return '—';try{return new Date(v).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(_){return String(v)}};
const safeUrl=v=>{try{const u=new URL(String(v||''),location.origin);return u.protocol==='https:'||u.origin===location.origin?u.href:''}catch(_){return ''}};
let loading=false,retryTimer=null;
function showLogin(msg=''){E('app').classList.add('hidden');E('login').classList.remove('hidden');E('loginError').textContent=msg}
function showApp(){E('login').classList.add('hidden');E('app').classList.remove('hidden')}
function reservationLabel(s){return ({preheld:'Pré-bloqué SWÉ',confirmed:'Réservé / confirmé',released:'Libéré',cancelled:'Annulé'})[String(s||'')]||'Non pré-bloqué'}
function reservationClass(s){return s==='confirmed'?'background:#dcfce7;color:#166534':s==='preheld'?'background:#fef3c7;color:#92400e':s==='released'?'background:#f3f4f6;color:#4b5563':'background:#f3f4f6;color:#4b5563'}
function networkState(){let b=E('complexNetwork4283');if(!b){b=document.createElement('div');b.id='complexNetwork4283';b.style.cssText='position:fixed;left:50%;bottom:14px;transform:translateX(-50%);z-index:9999;padding:9px 12px;border-radius:999px;background:#7f1d1d;color:white;font-weight:850;font-size:12px;display:none';b.textContent='Connexion interrompue • reconnexion automatique';document.body.appendChild(b)}b.style.display=navigator.onLine?'none':'block'}
async function rpcWithRetry(name,args={},attempts=2){let last;for(let i=0;i<attempts;i++){try{const r=await sb.rpc(name,args);if(!r.error)return r;last=r.error}catch(e){last=e}if(i<attempts-1)await new Promise(r=>setTimeout(r,450*(i+1)))}return {data:null,error:last||new Error('Service momentanément indisponible')}}
async function load(){if(loading)return;loading=true;clearTimeout(retryTimer);try{const r=await rpcWithRetry('get_my_complex_partner_dashboard',{},2);if(r.error)throw r.error;const cs=Array.isArray(r.data?.complexes)?r.data.complexes:[];if(!cs.length){E('content').innerHTML='<div class="card"><b>Aucun complexe partenaire n’est rattaché à ce compte.</b><div class="muted" style="margin-top:6px">Ton dossier doit être validé par SWÉ avant l’ouverture de l’espace partenaire.</div></div>';return}E('content').innerHTML=cs.map(c=>{
 const slots=Array.isArray(c.slots)?c.slots:[],packs=Array.isArray(c.packages)?c.packages:[],tours=Array.isArray(c.tournaments)?c.tournaments:[],plan=String(c.plan_code||'');
 const upcoming=tours.filter(t=>String(t.tournament_date||'')>=new Date(Date.now()-86400000).toISOString().slice(0,10));
 return '<section class="hero"><div class="status">COMPLEXE PARTENAIRE</div><h1>'+esc(c.name)+'</h1><div>'+esc([c.city,c.address].filter(Boolean).join(' • '))+'</div></section><div class="grid"><div class="card kpi"><span>Formule</span><b>'+esc(plan==='visibility_350'?'Visibilité':'Partenaire SWÉ')+'</b><div class="muted">'+money(c.monthly_fee_cents)+'/mois</div></div><div class="card kpi"><span>Swés à venir</span><b>'+upcoming.length+'</b><div class="muted">dans votre complexe</div></div><div class="card kpi"><span>Packs actifs</span><b>'+packs.filter(x=>x.active!==false).length+'</b><div class="muted">boissons & formules</div></div></div>'+
 '<div class="card section"><h2 style="margin-top:0">🏟️ Swés & paiements</h2><div class="muted" style="margin-bottom:10px">Dès le premier paiement en ligne validé, le créneau partenaire est confirmé et bloqué pour le Swé.</div>'+(tours.length?tours.map(t=>{const a=safeUrl(t.attendance_url);return '<div class="slot"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap"><div><b>'+esc(t.name||'Swé')+' • '+esc(t.tournament_date||'')+(t.start_time?' • '+String(t.start_time).slice(0,5):'')+'</b><div class="muted">'+esc(t.registered_count||0)+' inscrit(s) • '+esc(t.paid_count||0)+' paiement(s) en ligne • '+money(t.paid_cents||0)+' encaissé</div><div class="muted">Réf. '+esc(t.reservation_reference||'—')+(t.hold_expires_at?' • pré-blocage jusqu’au '+esc(dt(t.hold_expires_at)):'')+'</div></div><span style="'+reservationClass(t.reservation_status)+';padding:5px 8px;border-radius:999px;font-size:11px;font-weight:900">'+esc(reservationLabel(t.reservation_status))+'</span></div>'+(a?'<div style="margin-top:8px"><a href="'+esc(a)+'" target="_blank" rel="noopener noreferrer" style="font-weight:800;color:#0d7549">Voir la liste des inscrits / présence →</a></div>':'')+'</div>'}).join(''):'<div class="muted">Aucun Swé récent ou à venir.</div>')+'</div>'+
 '<div class="card section"><h2 style="margin-top:0">Profil public</h2><label class="field"><span>Accroche</span><input maxlength="180" data-tagline="'+esc(c.complex_id)+'" value="'+esc(c.public_tagline||'')+'"></label><label class="field"><span>Description</span><textarea maxlength="2000" rows="4" data-description="'+esc(c.complex_id)+'">'+esc(c.public_description||'')+'</textarea></label><label class="field"><span>Lien de réservation sécurisé</span><input maxlength="500" inputmode="url" data-booking="'+esc(c.complex_id)+'" value="'+esc(c.booking_url||'')+'" placeholder="https://..."></label><button class="primary" data-save="'+esc(c.complex_id)+'">Enregistrer</button></div><div class="grid section"><div class="card"><h2 style="margin-top:0">Créneaux proposés sur SWÉ</h2>'+(slots.length?slots.map(s=>'<div class="slot"><b>'+esc(days[Number(s.weekday)]||'Jour')+' '+String(s.start_time||'').slice(0,5)+'–'+String(s.end_time||'').slice(0,5)+'</b><div class="muted">'+esc(s.duration_minutes)+' min • '+esc(s.pitch_count)+' terrain(s) • prix membre SWÉ '+money(s.swe_public_price_cents)+'</div></div>').join(''):'<div class="muted">Aucun créneau configuré.</div>')+'</div><div class="card"><h2 style="margin-top:0">Packs & formules</h2>'+(packs.length?packs.map(p=>'<div class="pack"><b>'+esc(p.name)+' • '+money(p.public_price_cents)+'</b><div class="muted">'+esc(p.description||'')+(p.contains_alcohol?' • alcool':' • sans alcool')+'</div></div>').join(''):'<div class="muted">Aucun pack configuré.</div>')+'</div></div><div class="card section"><b>Confidentialité commerciale</b><div class="muted" style="margin-top:6px">Cet espace affiche uniquement les informations utiles au complexe. Les paramètres internes SWÉ, coûts internes et marges de la plateforme ne sont jamais affichés ici.</div></div>'
 }).join('');
 E('content').querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const id=b.dataset.save,book=E('content').querySelector('[data-booking="'+CSS.escape(id)+'"]').value.trim();if(book&&!/^https:\/\//i.test(book)){alert('Le lien de réservation doit commencer par https://');return}b.disabled=true;const r=await rpcWithRetry('complex_partner_update_public_profile',{p_complex_id:id,p_public_tagline:E('content').querySelector('[data-tagline="'+CSS.escape(id)+'"]').value,p_public_description:E('content').querySelector('[data-description="'+CSS.escape(id)+'"]').value,p_booking_url:book},2);b.disabled=false;if(r.error){alert(r.error.message||'Enregistrement impossible');return}b.textContent='Enregistré ✓';setTimeout(()=>b.textContent='Enregistrer',1200)});
}catch(e){E('content').innerHTML='<div class="card error"><b>Service momentanément indisponible.</b><div class="muted" style="margin-top:6px">SWÉ réessaie automatiquement.</div></div>';if(navigator.onLine)retryTimer=setTimeout(load,3000);console.warn('Portail complexe',e)}finally{loading=false}}
async function boot(){networkState();const {data,error}=await sb.auth.getSession();if(error)return showLogin('Connexion à vérifier.');if(data?.session){showApp();await load()}else showLogin()}
E('loginBtn').onclick=async()=>{if(!navigator.onLine)return showLogin('Connexion internet indisponible.');const b=E('loginBtn');b.disabled=true;E('loginError').textContent='Connexion…';const r=await sb.auth.signInWithPassword({email:E('email').value.trim(),password:E('password').value});b.disabled=false;if(r.error)return showLogin('Identifiants incorrects ou service indisponible.');showApp();await load()};E('password').addEventListener('keydown',e=>{if(e.key==='Enter')E('loginBtn').click()});E('logout').onclick=async()=>{await sb.auth.signOut({scope:'local'});showLogin()};
sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session)showLogin();});window.addEventListener('online',()=>{networkState();if(!E('app').classList.contains('hidden'))load()});window.addEventListener('offline',networkState);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!E('app').classList.contains('hidden'))load()});boot();
})();