-- Transactional fixtures: no persistent account, membership, match or score changes.
begin;
do $$
declare sa uuid; users uuid[]; ws uuid; other_ws uuid; ma uuid; mc uuid; data jsonb; recipients jsonb;
 scorer uuid; assister uuid; opponent uuid; goal uuid; fake_ws uuid;
begin
 select user_id into sa from public.platform_super_admins limit 1;
 select array_agg(user_id) into users from (select distinct user_id from public.global_player_profiles where user_id<>sa order by user_id limit 4) x;
 if cardinality(users)<>4 then raise exception 'Four existing accounts required for role checks'; end if;
 insert into public.workspaces(name,owner_user_id,public_enabled) values('Transactional permission fixture',users[1],false) returning id into ws;
 insert into public.workspaces(name,owner_user_id,public_enabled) values('Other transactional space',users[1],false) returning id into other_ws;
 insert into public.workspace_members(workspace_id,user_id,role,active) values(ws,users[1],'admin',true),(ws,users[2],'coorganizer',true),(ws,users[3],'coorganizer',true),(other_ws,users[2],'coorganizer',true);
 insert into public.coorganizer_permissions(workspace_id,user_id,can_enter_scores) values(ws,users[2],true),(ws,users[3],false),(other_ws,users[2],true);
 perform set_config('request.jwt.claim.sub',sa::text,true);execute 'set local role authenticated';
 recipients:=public.super_admin_get_test_match_recipients();
 if not exists(select 1 from jsonb_array_elements(recipients) r where r->>'workspace_id'=ws::text and r->>'user_id'=users[1]::text) then raise exception 'Admin missing from recipients'; end if;
 if not exists(select 1 from jsonb_array_elements(recipients) r where r->>'workspace_id'=ws::text and r->>'user_id'=users[2]::text) then raise exception 'Authorized coorganizer missing'; end if;
 if exists(select 1 from jsonb_array_elements(recipients) r where r->>'workspace_id'=ws::text and r->>'user_id'=users[3]::text) then raise exception 'Unauthorized coorganizer selectable'; end if;
 begin perform public.super_admin_create_test_match('{}',gen_random_uuid(),ws,users[3]);raise exception 'TEST_FAILED: unauthorized destination';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 begin perform public.super_admin_create_test_match('{}',gen_random_uuid(),ws,users[4]);raise exception 'TEST_FAILED: player destination';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 ma:=public.super_admin_create_test_match('{}',gen_random_uuid(),ws,users[1]);
 mc:=public.super_admin_create_test_match('{}',gen_random_uuid(),ws,users[2]);
 execute 'reset role';
 select workspace_id into fake_ws from private.match_test_runs where match_id=mc;
 if exists(select 1 from public.workspace_members where workspace_id=fake_ws) then raise exception 'Test leaked membership';end if;
 perform set_config('request.jwt.claim.sub',users[1]::text,true);execute 'set local role authenticated';
 if jsonb_array_length(public.get_my_workspace_test_matches(ws))<>1 then raise exception 'Admin list scope incorrect';end if;
 perform public.super_admin_test_match_action(ma,'start');
 begin perform public.super_admin_test_match_action(mc,'start');raise exception 'TEST_FAILED: wrong manager';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',users[2]::text,true);execute 'set local role authenticated';
 if jsonb_array_length(public.get_my_workspace_test_matches(ws))<>1 or jsonb_array_length(public.get_my_workspace_test_matches(other_ws))<>0 then raise exception 'Workspace scope incorrect';end if;
 data:=public.super_admin_test_match_action(mc,'start');
 if (data->>'can_edit')::boolean is not true then raise exception 'Assigned coorganizer cannot edit';end if;
 select (p->>'player_id')::uuid into scorer from jsonb_array_elements(data->'team_players') p where p->>'team_id'=data->'matches'->0->>'home_team_id' limit 1;
 select (p->>'player_id')::uuid into assister from jsonb_array_elements(data->'team_players') p where p->>'team_id'=data->'matches'->0->>'home_team_id' and p->>'player_id'<>scorer::text limit 1;
 select (p->>'player_id')::uuid into opponent from jsonb_array_elements(data->'team_players') p where p->>'team_id'=data->'matches'->0->>'away_team_id' limit 1;
 data:=public.super_admin_test_match_action(mc,'goal',scorer);goal:=(data->>'action_goal_id')::uuid;
 if goal is null then raise exception 'Quick goal ID missing';end if;
 perform public.super_admin_test_match_action(mc,'set_score',p_home_score=>3,p_away_score=>2);
 data:=public.super_admin_test_match_action(mc,'set_assist',p_goal_id=>goal,p_assister_id=>assister);
 if data->'matches'->0->>'home_score'<>'3' or data->'matches'->0->>'away_score'<>'2' then raise exception 'Assist overwrote manual score';end if;
 if not exists(select 1 from jsonb_array_elements(data->'goals') g where g->>'id'=goal::text and g->>'assister_player_id'=assister::text) then raise exception 'Quick assist missing';end if;
 begin perform public.super_admin_test_match_action(mc,'set_assist',p_goal_id=>goal,p_assister_id=>opponent);raise exception 'TEST_FAILED: opposite-team assist';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 begin perform public.super_admin_test_match_action(mc,'set_assist',p_goal_id=>goal,p_assister_id=>scorer);raise exception 'TEST_FAILED: self assist';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 begin perform public.super_admin_get_test_match_recipients();raise exception 'TEST_FAILED: recipient directory exposed';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 execute 'reset role';
 -- Revoke the actual workspace permission while the match remains live.
 update public.coorganizer_permissions set can_enter_scores=false where workspace_id=ws and user_id=users[2];
 perform set_config('request.jwt.claim.sub',users[2]::text,true);execute 'set local role authenticated';
 begin perform public.get_test_match_snapshot(mc);raise exception 'TEST_FAILED: revoked snapshot';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 begin perform public.super_admin_test_match_action(mc,'goal',scorer);raise exception 'TEST_FAILED: revoked scoring';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 begin perform public.get_my_workspace_test_matches(ws);raise exception 'TEST_FAILED: revoked listing';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',users[3]::text,true);execute 'set local role authenticated';
 begin perform public.super_admin_test_match_action(mc,'start');raise exception 'TEST_FAILED: unauthorized coorganizer';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',users[4]::text,true);execute 'set local role authenticated';
 begin perform public.get_test_match_snapshot(mc);raise exception 'TEST_FAILED: ordinary player';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
 execute 'reset role';
end $$;
rollback;
select 'Assigned admin/coorganizer, scope, quick scorer/assist and revocation passed; fixtures rolled back' as validation;
