begin;
do $$
declare tid uuid; uid uuid; voter uuid; s jsonb; p1 uuid; p2 uuid; tm uuid; captain uuid; guest uuid; original_rating numeric; ids uuid[]; got uuid[];
begin
 select t.id,wm.user_id into tid,uid from public.tournaments t join public.workspace_members wm on wm.workspace_id=t.workspace_id and wm.role='admin' and wm.active where t.name='TEST Glacière — 16/09/2026' limit 1;
 select wm.user_id into voter from public.workspace_members wm join public.tournament_players tp on tp.player_id=wm.linked_player_id and tp.tournament_id=tid where wm.role='coorganizer' and wm.active and tp.present limit 1;
 if tid is null or voter is null then raise exception 'Missing test fixture'; end if;
 select id into p1 from public.team_draw_room_proposals where tournament_id=tid order by sequence limit 1;
 select id into p2 from public.team_draw_room_proposals where tournament_id=tid order by sequence desc limit 1;
 if p1=p2 then raise exception 'Two proposals required'; end if;
 perform set_config('request.jwt.claim.sub',voter::text,true);
 execute 'set local role authenticated';
 s:=public.team_draw_room_vote_v1(tid,p1,'keep');
 s:=public.team_draw_room_vote_v1(tid,p2,'keep');
 if jsonb_array_length(s->'voters')<>0 then raise exception 'Voter names exposed';end if;
 if s->'my_final_choice'->>'proposal_id'<>p2::text then raise exception 'Wrong final choice';end if;
 execute 'reset role';
 if (select count(*) from public.team_draw_room_votes v join public.team_draw_room_proposals p on p.id=v.proposal_id where p.tournament_id=tid and v.user_id=voter)<>1 then raise exception 'Duplicate choices';end if;
 perform set_config('request.jwt.claim.sub',uid::text,true);
 execute 'set local role authenticated';
 s:=public.team_draw_room_state_v1(tid);
 if jsonb_array_length(s->'voters')=0 then raise exception 'Admin missing voter names';end if;
 execute 'reset role';
 select id into tm from public.teams where tournament_id=tid limit 1;
 select player_id into captain from public.team_players where team_id=tm limit 1;
 select player_id into guest from public.team_players where team_id=tm and player_id<>captain limit 1;
 select skill_level into original_rating from public.players where id=guest;
 update public.players set is_group_member=false,guest_of_player_id=captain where id=guest;
 if public.get_effective_player_rating(guest)<>2.5 then raise exception 'Guest estimate incorrect';end if;
 if (select skill_level from public.players where id=guest) is distinct from original_rating then raise exception 'Member rating mutated';end if;
 update public.teams set is_preformed=true,created_by_player_id=captain where id=tm;
 update public.tournaments set max_team_redraws=3,team_redraws_used=0 where id=tid;
 execute 'set local role authenticated';
 s:=public.team_draw_room_redraw_v1(tid);
 p1:=(s->>'current_proposal_id')::uuid;
 execute 'reset role';
 if not exists(select 1 from public.team_players where team_id=tm and player_id=captain) or not exists(select 1 from public.team_players where team_id=tm and player_id=guest) then raise exception 'Locked core moved';end if;
 select array_agg(player_id order by player_id) into ids from public.team_players where team_id=tm;
 if (select count(*) from public.team_players where team_id=tm and not private.is_locked_team_player_v4465(tm,player_id))<>3 then raise exception 'Random fillers incorrectly locked';end if;
 if exists(select 1 from jsonb_array_elements(s->'proposals'->0->'snapshot'->'teams') t where not t ? 'average_rating') then raise exception 'Missing averages';end if;
 execute 'set local role authenticated';
 s:=public.team_draw_room_redraw_v1(tid);
 perform public.team_draw_room_publish_v1(tid,p1);
 execute 'reset role';
 select array_agg(player_id order by player_id) into got from public.team_players where team_id=tm;
 if got is distinct from ids then raise exception 'Earlier proposal roster not restored';end if;
end $$;
rollback;
select 'PASS: privacy, final vote, guest estimate, fixed core, team averages, earlier proposal publication; all test changes rolled back' validation;
