begin;
do $$
declare v_admin uuid; v_ids text[]; v_match uuid; v_auto uuid; v_single uuid; v_auth_before bigint; v_profiles_before bigint; v_request uuid:=gen_random_uuid(); v_data jsonb; v_a uuid; v_b uuid; v_other uuid; v_team uuid; v_global_before bigint; v_global_after bigint; v_count bigint;
begin
  select user_id into v_admin from public.platform_super_admins limit 1;
  if v_admin is null then raise exception 'Aucun Super Admin pour le test'; end if;
  select array_agg(public_player_id) into v_ids from (select public_player_id from public.global_player_profiles where identity_status='active' order by public_player_id limit 4) p;
  if cardinality(v_ids)<4 then raise exception 'Quatre profils requis pour la validation'; end if;
  select count(*) into v_auth_before from auth.users;
  select count(*) into v_profiles_before from public.global_player_profiles;
  select count(*) into v_global_before from public.players where global_player_id is not null;
  perform set_config('request.jwt.claim.sub',v_admin::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',v_admin,'role','authenticated')::text,true);
  execute 'set local role authenticated';
  v_auto:=public.super_admin_create_test_match(array[]::text[],gen_random_uuid());
  v_data:=public.get_test_match_snapshot(v_auto);
  if jsonb_array_length(v_data->'players')<>12 or jsonb_array_length(v_data->'match_player_assignments')<>10 or (v_data->>'can_edit')::boolean is not true then raise exception 'Génération automatique incorrecte';end if;
  if exists(select 1 from jsonb_array_elements(v_data->'teams') t where (select count(*) from jsonb_array_elements(v_data->'team_players') p where p->>'team_id'=t->>'id')<>5) then raise exception 'Équipes automatiques déséquilibrées';end if;
  v_single:=public.super_admin_create_test_match(array[v_ids[1]],gen_random_uuid());
  if jsonb_array_length(public.get_test_match_snapshot(v_single)->'players')<>12 then raise exception 'Un compte ne suffit pas à lancer le test';end if;
  v_match:=public.super_admin_create_test_match(v_ids,v_request);
  if public.super_admin_create_test_match(v_ids,v_request)<>v_match then raise exception 'Idempotence incorrecte'; end if;
  v_data:=public.get_test_match_snapshot(v_match);
  if jsonb_array_length(v_data->'matches')<>1 or jsonb_array_length(v_data->'teams')<>2 or jsonb_array_length(v_data->'match_player_assignments')<>10 then raise exception 'Match incomplet'; end if;
  v_a:=(v_data->'match_player_assignments'->0->>'player_id')::uuid;v_team:=(v_data->'match_player_assignments'->0->>'team_id')::uuid;
  select (x->>'player_id')::uuid into v_b from jsonb_array_elements(v_data->'match_player_assignments') x where x->>'team_id'=v_team::text and x->>'player_id'<>v_a::text limit 1;
  select (x->>'player_id')::uuid into v_other from jsonb_array_elements(v_data->'match_player_assignments') x where x->>'team_id'<>v_team::text limit 1;
  begin perform public.super_admin_test_match_action(v_match,'goal',v_a,v_b);raise exception 'TEST_FAILED: but avant début autorisé';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
  perform public.super_admin_test_match_action(v_match,'start');
  begin perform public.super_admin_test_match_action(v_match,'goal',v_a,v_other);raise exception 'TEST_FAILED: passe adverse autorisée';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
  v_data:=public.super_admin_test_match_action(v_match,'goal',v_a,v_b);
  if (v_data->'matches'->0->>'home_score')::int+(v_data->'matches'->0->>'away_score')::int<>1 then raise exception 'Le déclencheur de score ne fonctionne pas'; end if;
  if v_data->'goals'->0->>'assister_player_id'<>v_b::text then raise exception 'Passeur non conservé';end if;
  v_data:=public.super_admin_test_match_action(v_match,'undo_goal');
  if jsonb_array_length(v_data->'goals')<>0 then raise exception 'Annulation incorrecte';end if;
  perform public.super_admin_test_match_action(v_match,'set_score',p_home_score=>3,p_away_score=>2);
  v_data:=public.super_admin_test_match_action(v_match,'goal',v_a,null);
  if (v_data->'matches'->0->>'home_score')::int+(v_data->'matches'->0->>'away_score')::int<>6 then raise exception 'Le but efface le score manuel';end if;
  v_data:=public.super_admin_test_match_action(v_match,'delete_goal',p_goal_id=>(v_data->'goals'->0->>'id')::uuid);
  if (v_data->'matches'->0->>'home_score')::int+(v_data->'matches'->0->>'away_score')::int<>5 or jsonb_array_length(v_data->'goals')<>0 then raise exception 'Annulation du but incorrecte';end if;
  begin perform public.super_admin_test_match_action(v_match,'delete_goal',p_goal_id=>gen_random_uuid());raise exception 'TEST_FAILED: but étranger accepté';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
  perform public.super_admin_test_match_action(v_match,'set_score',p_home_score=>0,p_away_score=>0);
  perform public.super_admin_test_match_action(v_match,'goal',v_a,null);
  v_data:=public.super_admin_test_match_action(v_match,'finish');
  if v_data->'matches'->0->>'status'<>'finished' then raise exception 'Fin non conservée'; end if;
  begin perform public.super_admin_test_match_action(v_match,'goal',v_a,null);raise exception 'TEST_FAILED: but après fin autorisé';exception when others then if sqlerrm like 'TEST_FAILED:%' then raise;end if;end;
  perform public.super_admin_get_page_reports();
  execute 'reset role';
  select count(*) into v_count from public.matches m join private.match_test_runs r on r.match_id=m.id where r.request_id=v_request;
  if v_count<>1 then raise exception 'Deux matchs ont été créés'; end if;
  select count(*) into v_global_after from public.players where global_player_id is not null;
  if (select count(*) from auth.users)<>v_auth_before or (select count(*) from public.global_player_profiles)<>v_profiles_before then raise exception 'Des comptes réels ont été créés';end if;
  if v_global_after<>v_global_before then raise exception 'Profils réels modifiés';end if;
  if exists(select 1 from public.workspace_members where workspace_id=(select workspace_id from private.match_test_runs where match_id=v_match)) then raise exception 'Le test apparaît dans un workspace personnel'; end if;
end $$;
rollback;
select 'Automatic match lifecycle and isolation passed; fixtures rolled back' as validation;
