const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('pwa-tournament-data-v5020.js','utf8');
function harness({standalone=true,fail=false,queue=[]}={}){
 let release;const calls=[];const S={session:{user:{id:'user'}},workspace:{id:'workspace'},activeTour:'test',tournaments:[{id:'test',reserved_pitch_ids:[]}],teams:[{id:'old'}],tPlayers:[],sportsPitches:[],workspaceFeatures:{}};
 const data={tournaments:{id:'test',reserved_pitch_ids:['king','middle','stream']},tournament_players:Array.from({length:30},()=>({present:true})),teams:Array.from({length:6},(_,i)=>({id:'team'+i})),matches:[],team_players:[]};
 const ctx={window:{matchMedia:()=>({matches:standalone})},navigator:{onLine:true,standalone},localStorage:{getItem:()=>JSON.stringify(queue)},document:{getElementById:()=>null,addEventListener(){}},S,renderMatchPitchSelect(){},loadTournament:async()=>calls.push('original'),sb:{rpc:async name=>({data:name==='get_sports_venues'?{pitches:[{id:'king',name:'Carrefour'}],complexes:[{id:'arena'}]}:[]}),from:table=>{const q={select(){return q},eq(){return q},single(){return q},order(){return q},in(){return q},then(resolve){if(table==='teams'&&fail)return Promise.resolve({error:{message:'Network failed'}}).then(resolve);if(table==='teams'&&ctx.hold)return new Promise(r=>{release=()=>r({data:data[table]})}).then(resolve);return Promise.resolve({data:data[table]}).then(resolve)}};return q}}};
 vm.createContext(ctx);vm.runInContext(src,ctx);return {ctx,calls,release:()=>release()};
}
test('ordinary website retains original loader',async()=>{const h=harness({standalone:false});await h.ctx.loadTournament();assert.deepEqual(h.calls,['original']);assert.equal(h.ctx.window.SWEPWATournamentData,undefined);});
test('PWA atomically refreshes real test roster and pitch configuration',async()=>{const {ctx}=harness();await ctx.loadTournament();assert.equal(ctx.S.teams.length,6);assert.equal(ctx.S.tPlayers.length,30);assert.equal(ctx.S.tournaments[0].reserved_pitch_ids.length,3);assert.equal(ctx.S.sportsPitches[0].name,'Carrefour');});
test('failed roster read preserves prior state',async()=>{const {ctx}=harness({fail:true});await assert.rejects(ctx.loadTournament(),/Network failed/);assert.equal(ctx.S.teams[0].id,'old');assert.equal(ctx.S.tournaments[0].reserved_pitch_ids.length,0);});
test('pending offline actions are retained and prevent overwriting local state',async()=>{const {ctx}=harness({queue:[{user_id:'user',workspace_id:'workspace',type:'update_match_score'}]});await assert.rejects(ctx.loadTournament(),/synchronisation/);assert.equal(ctx.S.teams[0].id,'old');assert.match(ctx.localStorage.getItem(),/update_match_score/);});
test('response for former selected tournament cannot overwrite the new one',async()=>{const h=harness();h.ctx.hold=true;const promise=h.ctx.loadTournament();await new Promise(r=>setImmediate(r));h.ctx.S.activeTour='other';h.release();assert.equal(await promise,false);assert.equal(h.ctx.S.teams[0].id,'old');});
