'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('./engine.cjs'),{command}=require('./server.cjs');
const base=()=>({entitled:true,admin:true,can_score:true,locked:true,pitch_count:3,teams:['a','b','c','d','e','f'],version:0,state:null,matches:[]});
function repo(c){return {context:async()=>structuredClone(c),commit:async(t,u,v,s)=>{if(c.version!==v)throw Error('Version modifiée');c.version++;c.state=s;return s}}}
test('authorization and subscription rechecked before every state change',async()=>{for(const patch of [{entitled:false},{admin:false},{locked:false},{pitch_count:2}]){const c={...base(),...patch};await assert.rejects(command(repo(c),'u',{tournamentId:'t',action:'start'}));assert.equal(c.version,0)}});
test('never accepts a forged client state',async()=>{const c=base(),s=await command(repo(c),'u',{tournamentId:'t',action:'start',state:{phase:'finished'}});assert.equal(s.phase,'qualification');assert.equal(s.matches.length,6)});
test('designated scorer cannot draw or correct',async()=>{const c=base();c.state=E.create(c.teams);c.admin=false;c.matches=[{format_slot:'fast:q1_1',home_score:1,away_score:0,captains_confirmed:false}];for(const action of ['draw','validate_draw','correct'])await assert.rejects(command(repo(c),'u',{tournamentId:'t',action,matchId:'q1_1'}));assert.equal(c.version,0)});
test('finish uses stored score and not a forged request score',async()=>{const c=base();c.state=E.create(c.teams);c.matches=[{format_slot:'fast:q1_1',home_score:1,away_score:0,captains_confirmed:true}];const s=await command(repo(c),'u',{tournamentId:'t',action:'finish',matchId:'q1_1',homeScore:99});assert.equal(s.matches[0].homeScore,1)});
test('authorized scorer can finish without captains, using the stored score',async()=>{const c=base();c.admin=false;c.state=E.create(c.teams);c.matches=[{format_slot:'fast:q1_1',home_score:2,away_score:1,captains_confirmed:false}];const s=await command(repo(c),'u',{tournamentId:'t',action:'finish',matchId:'q1_1',homeScore:99});assert.equal(s.matches[0].status,'finished');assert.equal(s.matches[0].homeScore,2)});
test('optimistic version rejects concurrent completion without losing data',async()=>{const c=base(),r=repo(c);const results=await Promise.allSettled([command(r,'u',{tournamentId:'t',action:'start'}),command(r,'u',{tournamentId:'t',action:'start'})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(c.version,1)});
test('unauthenticated and unknown actions rejected',async()=>{await assert.rejects(command(repo(base()),null,{tournamentId:'t',action:'start'}));await assert.rejects(command(repo(base()),'u',{tournamentId:'t',action:'inject'}))});
