'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
function app(context){const d=new JSDOM('<select id="tourFormat"><option value="classic">Classique</option></select><section id="tournamentAdminCard"></section><div id="matchesList"></div>',{runScripts:'outside-only'}),w=d.window;const teams=['a','b','c','d','e','f'].map(id=>({id,name:'Équipe '+id}));w.S={workspaceFeatures:{tournaments_enabled:true},teams,coorgs:[],players:[],teamPlayers:[],session:{user:{id:'u'}},tPlayers:[],matchAssignments:[]};w.currentTour=()=>({id:'t',format:'fast_conquest'});w.toast=()=>{};w.loadTournament=async()=>{};w.sb={rpc:async()=>({data:context})};w.eval(fs.readFileSync('fast-conquest/browser-engine.js','utf8'));w.eval(fs.readFileSync('fast-conquest/ui.js','utf8'));return d;}
const c=()=>({admin:true,entitled:true,can_score:true,locked:false,version:0,pitch_count:3,mode:'admin',state:null,evaluators:[],votes:[],captains:[],captain_candidates:[],my_notes:[],note_summary:[]});
test('qualification tie exposes draw and validation outside collapsed settings',async()=>{const E=require('./engine.cjs'),state=E.create(['a','b','c','d','e','f']);for(const id of state.matches.map(m=>m.id))E.finish(state,id,{homeScore:0,awayScore:0});for(const drawn of [false,true]){if(drawn)E.proposeDraw(state,()=>.2);const d=app({...c(),state});try{await new Promise(r=>setTimeout(r,10));const next=d.window.document.querySelector('.fast-next-phase');assert.ok(next);assert.equal(next.closest('details'),null);assert.match(next.textContent,drawn?/Valider et générer Conquête 1/:/Départager les équipes à égalité/);}finally{d.window.close()}}});
test('running tournament keeps only a compact header above matches and folds progression',async()=>{const state=require('./engine.cjs').create(['a','b','c','d','e','f']),d=app({...c(),state});try{await new Promise(r=>setTimeout(r,10));const panel=d.window.document.getElementById('fastConquestPanel'),overview=panel.querySelector('[data-fast-overview]');assert.equal(overview.open,false);assert.match(panel.firstElementChild.textContent,/Fast Conquête.*Qualifications.*Actualiser/);assert.equal(panel.querySelectorAll('button').length>0,true);assert.ok(overview.querySelector('p'));}finally{d.window.close()}});
test('creation format and organizer controls appear; refresh retains identical DOM',async()=>{const d=app(c()),w=d.window;await new Promise(r=>setTimeout(r,10));assert.ok(w.document.querySelector('option[value="fast_conquest"]'));const panel=w.document.getElementById('fastConquestPanel'),button=panel.querySelector('button');assert.match(panel.textContent,/Verrouiller les équipes/);await w.SWE_FAST_CONQUEST.refresh();assert.equal(panel.querySelector('button'),button);d.window.close()});
test('selected co-manager opens existing five-draw salon without organizer controls',async()=>{const context={...c(),admin:false,mode:'collaborative',evaluators:['u']};const d=app(context),w=d.window;try{let opened=null;w.SWETeamDrawSalonV2={open:id=>opened=id};await new Promise(r=>setTimeout(r,10));const panel=w.document.getElementById('fastConquestPanel');assert.match(panel.textContent,/Ouvrir le salon · 5 tirages/);assert.doesNotMatch(panel.textContent,/Lancer les qualifications|Verrouiller les équipes/);[...panel.querySelectorAll('button')].find(b=>b.textContent.includes('5 tirages')).click();assert.equal(opened,'t');}finally{w.close()}});
test('future rounds remain blocked; authorized scorers finish without captain validation',async()=>{for(const admin of [false,true]){const context={...c(),admin,matches:[{id:'m',captains_confirmed:false}]},d=app(context);await new Promise(r=>setTimeout(r,10));const ui=d.window.SWE_FAST_CONQUEST;let node=ui.finishControl({id:'m',pitch:null},true,false);assert.match(node.textContent,/Tour précédent/);node=ui.finishControl({id:'m',pitch:'Carrefour'},true,false);assert.equal([...node.querySelectorAll('button')].find(b=>b.textContent==='Terminer le match').disabled,false);assert.doesNotMatch(node.textContent,/capitaine/i);d.window.close()}});
test('public live shows complete ranking and never private notes or votes',()=>{const d=new JSDOM('<div id="liveCoorgRating"></div><h2 id="liveRankingTitle"></h2><div id="liveRanking"></div>',{runScripts:'outside-only'}),w=d.window;w.eval(fs.readFileSync('fast-conquest/browser-engine.js','utf8'));w.eval(fs.readFileSync('fast-conquest/live.js','utf8'));const E=require('./engine.cjs'),teams=['a','b','c','d','e','f'],s=E.create(teams);while(s.phase!=='finished'){for(const id of s.matches.filter(m=>m.phase===s.phase&&m.status!=='finished').map(m=>m.id))E.finish(s,id,{homeScore:1,awayScore:0});if(s.phase==='qualification'){E.proposeDraw(s,()=>.2);E.validateDraw(s,'u')}}w.SWE_FAST_LIVE({format:'fast_conquest',rotation_state:{fast_conquest:s}},teams.map(id=>({id,name:id})));assert.equal(w.document.querySelectorAll('.fast-podium-card').length,3);assert.equal(w.document.querySelectorAll('.fast-rank-card').length,3);assert.match(w.document.body.textContent,/Champion et/);assert.doesNotMatch(w.document.body.textContent,/Commentaire confidentiel|my_notes|votes/);w.close()});

test('public live reveals fifth and sixth places while finals remain undecided',()=>{const d=new JSDOM('<div id="liveCoorgRating"></div><h2 id="liveRankingTitle"></h2><div id="liveRanking"></div>',{runScripts:'outside-only'}),w=d.window;w.eval(fs.readFileSync('fast-conquest/browser-engine.js','utf8'));w.eval(fs.readFileSync('fast-conquest/live.js','utf8'));const E=require('./engine.cjs'),teams=['a','b','c','d','e','f'],s=E.create(teams);for(const id of s.matches.map(m=>m.id))E.finish(s,id,{homeScore:1,awayScore:0});if(s.phase==='qualification'){E.proposeDraw(s,()=>.2);E.validateDraw(s,'u')}for(const id of s.matches.filter(m=>m.phase==='conquest_1').map(m=>m.id))E.finish(s,id,{homeScore:1,awayScore:0});for(const id of s.matches.filter(m=>m.phase==='conquest_2').map(m=>m.id))E.finish(s,id,{homeScore:1,awayScore:0});assert.equal(s.phase,'finals');w.SWE_FAST_LIVE({format:'fast_conquest',rotation_state:{fast_conquest:s}},teams.map(id=>({id,name:id})));const text=w.document.querySelector('.fast-live-ranking').textContent;assert.match(text,/1er–2e/);assert.match(text,/3e–4e/);assert.match(text,/5e.*Place définitive/);assert.match(text,/6e.*Place définitive/);assert.equal(w.document.querySelectorAll('.fast-rank-card').length,6);w.close()});

test('collaborative organizer reuses legacy salon instead of creating a second vote panel',async()=>{const d=app({...c(),mode:'collaborative'}),w=d.window;try{await new Promise(r=>setTimeout(r,10));const panel=w.document.getElementById('fastConquestPanel');assert.match(panel.textContent,/Ouvrir le salon · 5 tirages/);assert.doesNotMatch(panel.textContent,/Ouvrir une nouvelle proposition|Demander une modification/);assert.equal([...panel.querySelectorAll('button')].find(b=>b.textContent==='Verrouiller les équipes').disabled,true);}finally{w.close()}});
