'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
function app(context){const d=new JSDOM('<select id="tourFormat"><option value="classic">Classique</option></select><section id="tournamentAdminCard"></section><div id="matchesList"></div>',{runScripts:'outside-only'}),w=d.window;const teams=['a','b','c','d','e','f'].map(id=>({id,name:'Équipe '+id}));w.S={workspaceFeatures:{tournaments_enabled:true},teams,coorgs:[],players:[],teamPlayers:[],session:{user:{id:'u'}},tPlayers:[],matchAssignments:[]};w.currentTour=()=>({id:'t',format:'fast_conquest'});w.toast=()=>{};w.loadTournament=async()=>{};w.sb={rpc:async()=>({data:context})};w.eval(fs.readFileSync('fast-conquest/browser-engine.js','utf8'));w.eval(fs.readFileSync('fast-conquest/ui.js','utf8'));return d;}
const c=()=>({admin:true,entitled:true,can_score:true,locked:false,version:0,pitch_count:3,mode:'admin',state:null,evaluators:[],votes:[],captains:[],captain_candidates:[],my_notes:[],note_summary:[]});
test('creation format and organizer controls appear; refresh retains identical DOM',async()=>{const d=app(c()),w=d.window;await new Promise(r=>setTimeout(r,10));assert.ok(w.document.querySelector('option[value="fast_conquest"]'));const panel=w.document.getElementById('fastConquestPanel'),button=panel.querySelector('button');assert.match(panel.textContent,/Verrouiller les équipes/);await w.SWE_FAST_CONQUEST.refresh();assert.equal(panel.querySelector('button'),button);d.window.close()});
test('co-manager cannot launch or lock; active confidential voting is visible',async()=>{const context={...c(),admin:false,mode:'collaborative',vote_open:true,evaluators:['u']};const d=app(context);await new Promise(r=>setTimeout(r,10));const text=d.window.document.getElementById('fastConquestPanel').textContent;assert.match(text,/Salon de vote/);assert.match(text,/Valider la proposition/);assert.doesNotMatch(text,/Lancer les qualifications|Verrouiller les équipes/);d.window.close()});
test('future rounds cannot finish; missing captain confirmation disables finishing',async()=>{const context={...c(),matches:[{id:'m',captains_confirmed:false}]},d=app(context);await new Promise(r=>setTimeout(r,10));const ui=d.window.SWE_FAST_CONQUEST;let node=ui.finishControl({id:'m',pitch:null},true,false);assert.match(node.textContent,/Tour précédent/);node=ui.finishControl({id:'m',pitch:'Carrefour'},true,false);assert.equal([...node.querySelectorAll('button')].find(b=>b.textContent==='Terminer le match').disabled,true);d.window.close()});
test('public live shows complete ranking and never private notes or votes',()=>{const d=new JSDOM('<div id="liveCoorgRating"></div><h2 id="liveRankingTitle"></h2><div id="liveRanking"></div>',{runScripts:'outside-only'}),w=d.window;w.eval(fs.readFileSync('fast-conquest/browser-engine.js','utf8'));w.eval(fs.readFileSync('fast-conquest/live.js','utf8'));const E=require('./engine.cjs'),teams=['a','b','c','d','e','f'],s=E.create(teams);while(s.phase!=='finished'){for(const id of s.matches.filter(m=>m.phase===s.phase&&m.status!=='finished').map(m=>m.id))E.finish(s,id,{homeScore:1,awayScore:0});if(s.phase==='qualification'){E.proposeDraw(s,()=>.2);E.validateDraw(s,'u')}}w.SWE_FAST_LIVE({format:'fast_conquest',rotation_state:{fast_conquest:s}},teams.map(id=>({id,name:id})));assert.equal(w.document.querySelectorAll('#liveRanking tr').length,7);assert.match(w.document.body.textContent,/Champion et/);assert.doesNotMatch(w.document.body.textContent,/Commentaire confidentiel|my_notes|votes/);w.close()});

test('another vote updates the count without losing an unsaved comment',async()=>{const context={...c(),admin:false,mode:'collaborative',vote_open:true,evaluators:['u']},d=app(context),w=d.window;await new Promise(r=>setTimeout(r,10));w.document.querySelector('textarea').value='Pending exchange explanation';context.version=1;context.votes.push({decision:'approve'});await w.SWE_FAST_CONQUEST.refresh(true);assert.equal(w.document.querySelector('textarea').value,'Pending exchange explanation');assert.match(w.document.getElementById('fastConquestPanel').textContent,/1 validations/);w.close()});
